services:
  floci:
    image: floci/floci:latest
    container_name: floci
    privileged: true
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  floci-ui:
    image: floci/floci-ui:latest
    container_name: floci-ui
    ports:
      - "4500:4500"
    depends_on:
      - floci
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      AWS_ENDPOINT_URL: http://floci:4566